### ISSUE TITLE
How does this script work?

### ISSUE THREAD

**Issue by Mister-Curious** [Reasel/AHK-LIFX#1]
I have entered my token on line 3, then executed the script and nothing happens. Is there supposed to be some GUIor something? Have you any videos of this working? This looks promising but its literally doing nothing when I launch the script. 

Thanks!

**Comment by Reasel** [comment]
Hello! The LIFX.ahk script is meant to be included in your own scripts and then you can create an object to control your lights as in the example script.
From the example script
`MyLight := new LIFXLight("Ragnar") ; `

You would replace Ragnar with the name of your light and then you can control it in your scripts.

There is no GUI. This project just grants you control over your lights. You are free to create your own gui for controls as you see fit.

**Comment by Reasel** [comment]
I did just update the readme to hopefully better explain how to run things, but maybe I didn't explain what this script is. 

There is no gui. This just allows you to create an object that can control your LIFX lights. No gui. No automated name grabbing or anything. Just lets you control your lights by name and access the LIFX api via easier AHK object function calls.
